#!/usr/bin/env python
import argparse
from pathlib import Path
import _bootstrap
from predictor.training import train
from predictor.reproducibility import load_preset
def main(argv=None):
 p=argparse.ArgumentParser();p.add_argument("--results-dir",type=Path,required=True);p.add_argument("--layer",type=int,required=True);p.add_argument("--preset",choices=["phase4_d64_ce_baseline"]);p.add_argument("--model",choices=["factorized","residual_factorized","mlp"],default="factorized");p.add_argument("--latent-dim",type=int,default=128);p.add_argument("--loss",default="distribution_ce");p.add_argument("--run-name");p.add_argument("--init-checkpoint",type=Path);p.add_argument("--device",default="cuda");p.add_argument("--epochs",type=int,default=100);p.add_argument("--patience",type=int,default=10);p.add_argument("--no-early-stopping",action="store_true");p.add_argument("--batch-size",type=int,default=16);p.add_argument("--lr",type=float);p.add_argument("--weight-decay",type=float,default=1e-4);p.add_argument("--dropout",type=float,default=.1);p.add_argument("--seed",type=int,default=42);p.add_argument("--checkpoint-objective",choices=["validation_captured_mass","validation_distribution_ce","validation_output_score"]);p.add_argument("--freeze-encoder-epochs",type=int,default=0);p.add_argument("--min-validation-p01",type=float);p.add_argument("--train-retention",type=float,default=.5);p.add_argument("--ste-temperature-start",type=float,default=1.);p.add_argument("--ste-temperature-end",type=float,default=.1);p.add_argument("--ste-normalize-logits",action=argparse.BooleanOptionalAction,default=True);p.add_argument("--amp",action=argparse.BooleanOptionalAction,default=True);p.add_argument("--cosine-weight",type=float,default=1.);p.add_argument("--relative-weight",type=float,default=.25);p.add_argument("--ranking-weight",type=float,default=.05);a=p.parse_args(argv)
 if a.preset:
  preset=load_preset(a.preset);a.model=preset["model"];a.latent_dim=preset["latent_dim"];a.loss=preset["loss"];a.seed=preset["seed"];a.epochs=preset["epochs"];a.batch_size=preset["batch_size"];a.lr=preset["learning_rate"];a.weight_decay=preset["weight_decay"];a.dropout=preset["dropout"];a.patience=preset["patience"];a.amp=preset["amp"];a.checkpoint_objective=preset["checkpoint_objective"];a.no_early_stopping=not preset["early_stopping"]
 if a.run_name:name=a.run_name
 elif a.init_checkpoint:
  suffix=f"_freeze{a.freeze_encoder_epochs}" if a.freeze_encoder_epochs else "";name=f"{a.model}_d{a.latent_dim}_ce_to_hybrid_rank_rw{round(a.ranking_weight*100):03d}{suffix}"
 else:name=f"{a.model}_d{a.latent_dim}_{a.loss}"
 print(train(a.results_dir/f"layer_{a.layer:03d}/targets",a.results_dir/f"layer_{a.layer:03d}/{name}",kind=a.model,latent_dim=a.latent_dim,loss=a.loss,device=a.device,epochs=a.epochs,batch_size=a.batch_size,lr=a.lr,weight_decay=a.weight_decay,dropout=a.dropout,patience=a.patience,seed=a.seed,train_retention=a.train_retention,temperature_start=a.ste_temperature_start,temperature_end=a.ste_temperature_end,ste_normalize=a.ste_normalize_logits,cosine_weight=a.cosine_weight,relative_weight=a.relative_weight,ranking_weight=a.ranking_weight,amp=a.amp,init_checkpoint=a.init_checkpoint,freeze_encoder_epochs=a.freeze_encoder_epochs,min_validation_p01=a.min_validation_p01,early_stopping=not a.no_early_stopping,checkpoint_objective=a.checkpoint_objective,shuffle_strategy=preset["shuffle"] if a.preset else "global_rng_torch_randperm"))
if __name__=="__main__":main()
